<?php

namespace Database\Seeders;

use App\Models\Huruf;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class HurufSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('hurufs')->insert([
            /*=================== HiRAGANA GOJUON START =================== */
            //a groups
           // a groups
[
    'id' => 'H-GO-A',
    'huruf' => 'あ',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'あ adalah huruf vokal dasar yang sering digunakan dalam kata-kata sederhana seperti sapaan dan nama. Dilafalkan seperti "a" pada kata "anak".',
    'romaji' => 'a',
    'jumlah_coretan' => 3,
    'kategori' => 'vokal',
    'groups' => 'a',
    'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748774537/52_tjmkqe.wav',
    'catatan' => 'Huruf dasar yang sering muncul di awal belajar bahasa Jepang.',
    'urutan' => 1,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-I',
    'huruf' => 'い',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'い biasa ditemukan dalam kata sapaan seperti いえ (rumah) atau いぬ (anjing). Dilafalkan seperti "i" dalam "ibu".',
    'romaji' => 'i',
    'jumlah_coretan' => 2,
    'kategori' => 'vokal',
    'groups' => 'a',
    'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748774571/52_1_tk3gw0.wav',
    'catatan' => 'Bentuknya sederhana dan mudah diingat.',
    'urutan' => 2,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-U',
    'huruf' => 'う',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'う digunakan dalam banyak kata kerja dan juga untuk memanjangkan bunyi vokal. Pelafalannya seperti "u" pada kata "ular".',
    'romaji' => 'u',
    'jumlah_coretan' => 2,
    'kategori' => 'vokal',
    'groups' => 'a',
    'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748776447/53_1_lb67yt.wav',
    'catatan' => 'Huruf ini sering digunakan untuk memanjangkan bunyi vokal.',
    'urutan' => 3,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-E',
    'huruf' => 'え',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'え sering muncul dalam kata benda atau sapaan seperti えき (stasiun). Dilafalkan seperti "e" dalam "enak".',
    'romaji' => 'e',
    'jumlah_coretan' => 2,
    'kategori' => 'vokal',
    'groups' => 'a',
    'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748774751/52_2_razo63.wav',
    'catatan' => 'Salah satu huruf vokal dasar yang penting dikuasai.',
    'urutan' => 4,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-O',
    'huruf' => 'お',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'お sering dipakai dalam kata-kata sopan seperti おはよう (selamat pagi). Diucapkan seperti "o" dalam "orang".',
    'romaji' => 'o',
    'jumlah_coretan' => 3,
    'kategori' => 'vokal',
    'groups' => 'a',
    'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748774874/52_3_pwsr09.wav',
    'catatan' => 'Huruf penting yang sering digunakan dalam sapaan bahasa Jepang.',
    'urutan' => 5,
    'created_at' => $now,
    'updated_at' => $now,
],

            //end a groups

            // ka groups
[
    'id' => 'H-GO-KA',
    'huruf' => 'か',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'か adalah huruf konsonan dengan bunyi "ka", sering digunakan dalam kosakata dasar seperti benda dan tempat.',
    'romaji' => 'ka',
    'jumlah_coretan' => 3,
    'kategori' => 'konsonan',
    'groups' => 'ka',
    'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748775051/52_xlwkfb.wav',
    'catatan' => 'Termasuk dalam kelompok konsonan "k". Pelafalannya mirip dengan "ka" pada kata "kaki".',
    'urutan' => 6,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-KI',
    'huruf' => 'き',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'き adalah huruf yang mewakili bunyi "ki", sering muncul dalam kata sifat dan benda.',
    'romaji' => 'ki',
    'jumlah_coretan' => 4,
    'kategori' => 'konsonan',
    'groups' => 'ka',
    'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748775088/52_1_qdvflo.wav',
    'catatan' => 'Huruf ini punya bentuk khas yang sering dipakai dalam kata sifat.',
    'urutan' => 7,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-KU',
    'huruf' => 'く',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'く merupakan huruf dengan bunyi "ku", bentuknya simpel dan sering dijumpai dalam kata kerja.',
    'romaji' => 'ku',
    'jumlah_coretan' => 1,
    'kategori' => 'konsonan',
    'groups' => 'ka',
    'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748775123/52_2_nrfhy5.wav',
    'catatan' => 'Termasuk huruf dengan satu coretan yang mudah ditulis.',
    'urutan' => 8,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-KE',
    'huruf' => 'け',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'け melambangkan bunyi "ke" dan sering digunakan dalam nama orang dan tempat.',
    'romaji' => 'ke',
    'jumlah_coretan' => 3,
    'kategori' => 'konsonan',
    'groups' => 'ka',
    'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748775158/52_3_aggmko.wav',
    'catatan' => 'Bentuknya menyerupai angka 7 dengan tambahan coretan.',
    'urutan' => 9,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-KO',
    'huruf' => 'こ',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'こ adalah huruf yang mewakili bunyi "ko", sering digunakan dalam kata tunjuk dan nama.',
    'romaji' => 'ko',
    'jumlah_coretan' => 2,
    'kategori' => 'konsonan',
    'groups' => 'ka',
    'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748775194/52_4_xwpfav.wav',
    'catatan' => 'Bentuknya sederhana dan mudah dikenali pemula.',
    'urutan' => 10,
    'created_at' => $now,
    'updated_at' => $now,
],
// end ka groups


           // sa groups
[
    'id' => 'H-GO-SA',
    'huruf' => 'さ',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "s" pertama dalam hiragana.',
    'romaji' => 'sa',
    'jumlah_coretan' => 3,
    'kategori' => 'konsonan',
    'groups' => 'sa',
    'audio' => null,
    'catatan' => null,
    'urutan' => 11,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-SHI',
    'huruf' => 'し',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "s" kedua dalam hiragana. Dibaca "shi", bukan "si".',
    'romaji' => 'shi',
    'jumlah_coretan' => 1,
    'kategori' => 'konsonan',
    'groups' => 'sa',
    'audio' => null,
    'catatan' => null,
    'urutan' => 12,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-SU',
    'huruf' => 'す',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "s" ketiga dalam hiragana.',
    'romaji' => 'su',
    'jumlah_coretan' => 2,
    'kategori' => 'konsonan',
    'groups' => 'sa',
    'audio' => null,
    'catatan' => null,
    'urutan' => 13,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-SE',
    'huruf' => 'せ',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "s" keempat dalam hiragana.',
    'romaji' => 'se',
    'jumlah_coretan' => 3,
    'kategori' => 'konsonan',
    'groups' => 'sa',
    'audio' => null,
    'catatan' => null,
    'urutan' => 14,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-SO',
    'huruf' => 'そ',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "s" kelima dalam hiragana.',
    'romaji' => 'so',
    'jumlah_coretan' => 2,
    'kategori' => 'konsonan',
    'groups' => 'sa',
    'audio' => null,
    'catatan' => null,
    'urutan' => 15,
    'created_at' => $now,
    'updated_at' => $now,
],
// end sa groups


            // ta groups
[
    'id' => 'H-GO-TA',
    'huruf' => 'た',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "t" pertama dalam hiragana.',
    'romaji' => 'ta',
    'jumlah_coretan' => 4,
    'kategori' => 'konsonan',
    'groups' => 'ta',
    'audio' => null,
    'catatan' => null,
    'urutan' => 16,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-CHI',
    'huruf' => 'ち',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "ch" dalam hiragana.',
    'romaji' => 'chi',
    'jumlah_coretan' => 3,
    'kategori' => 'konsonan',
    'groups' => 'ta',
    'audio' => null,
    'catatan' => null,
    'urutan' => 17,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-TSU',
    'huruf' => 'つ',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "ts" dalam hiragana.',
    'romaji' => 'tsu',
    'jumlah_coretan' => 2,
    'kategori' => 'konsonan',
    'groups' => 'ta',
    'audio' => null,
    'catatan' => null,
    'urutan' => 18,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-TE',
    'huruf' => 'て',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "t" kedua dalam hiragana.',
    'romaji' => 'te',
    'jumlah_coretan' => 1,
    'kategori' => 'konsonan',
    'groups' => 'ta',
    'audio' => null,
    'catatan' => null,
    'urutan' => 19,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-TO',
    'huruf' => 'と',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "t" terakhir dalam hiragana.',
    'romaji' => 'to',
    'jumlah_coretan' => 2,
    'kategori' => 'konsonan',
    'groups' => 'ta',
    'audio' => null,
    'catatan' => null,
    'urutan' => 20,
    'created_at' => $now,
    'updated_at' => $now,
],
// end ta groups

// na groups
[
    'id' => 'H-GO-NA',
    'huruf' => 'な',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "n" pertama dalam hiragana.',
    'romaji' => 'na',
    'jumlah_coretan' => 4,
    'kategori' => 'konsonan',
    'groups' => 'na',
    'audio' => null,
    'catatan' => null,
    'urutan' => 21,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-NI',
    'huruf' => 'に',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "n" kedua dalam hiragana.',
    'romaji' => 'ni',
    'jumlah_coretan' => 3,
    'kategori' => 'konsonan',
    'groups' => 'na',
    'audio' => null,
    'catatan' => null,
    'urutan' => 22,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-NU',
    'huruf' => 'ぬ',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "n" ketiga dalam hiragana.',
    'romaji' => 'nu',
    'jumlah_coretan' => 2,
    'kategori' => 'konsonan',
    'groups' => 'na',
    'audio' => null,
    'catatan' => null,
    'urutan' => 23,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-NE',
    'huruf' => 'ね',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "n" keempat dalam hiragana.',
    'romaji' => 'ne',
    'jumlah_coretan' => 2,
    'kategori' => 'konsonan',
    'groups' => 'na',
    'audio' => null,
    'catatan' => null,
    'urutan' => 24,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-NO',
    'huruf' => 'の',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "n" terakhir dalam hiragana.',
    'romaji' => 'no',
    'jumlah_coretan' => 1,
    'kategori' => 'konsonan',
    'groups' => 'na',
    'audio' => null,
    'catatan' => null,
    'urutan' => 25,
    'created_at' => $now,
    'updated_at' => $now,
],
// end na groups

            

            // ha groups
[
    'id' => 'H-GO-HA',
    'huruf' => 'は',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "h" pertama dalam hiragana.',
    'romaji' => 'ha',
    'jumlah_coretan' => 3,
    'kategori' => 'konsonan',
    'groups' => 'ha',
    'audio' => null,
    'catatan' => null,
    'urutan' => 26,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-HI',
    'huruf' => 'ひ',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "h" kedua dalam hiragana.',
    'romaji' => 'hi',
    'jumlah_coretan' => 2,
    'kategori' => 'konsonan',
    'groups' => 'ha',
    'audio' => null,
    'catatan' => null,
    'urutan' => 27,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-FU',
    'huruf' => 'ふ',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "f" dalam hiragana, dibaca "fu".',
    'romaji' => 'fu',
    'jumlah_coretan' => 1,
    'kategori' => 'konsonan',
    'groups' => 'ha',
    'audio' => null,
    'catatan' => null,
    'urutan' => 28,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-HE',
    'huruf' => 'へ',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "h" keempat dalam hiragana.',
    'romaji' => 'he',
    'jumlah_coretan' => 1,
    'kategori' => 'konsonan',
    'groups' => 'ha',
    'audio' => null,
    'catatan' => null,
    'urutan' => 29,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-HO',
    'huruf' => 'ほ',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "h" terakhir dalam hiragana.',
    'romaji' => 'ho',
    'jumlah_coretan' => 4,
    'kategori' => 'konsonan',
    'groups' => 'ha',
    'audio' => null,
    'catatan' => null,
    'urutan' => 30,
    'created_at' => $now,
    'updated_at' => $now,
],
// end ha groups

  // ma groups
[
    'id' => 'H-GO-MA',
    'huruf' => 'ま',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "m" pertama dalam hiragana.',
    'romaji' => 'ma',
    'jumlah_coretan' => 3,
    'kategori' => 'konsonan',
    'groups' => 'ma',
    'audio' => null,
    'catatan' => null,
    'urutan' => 31,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-MI',
    'huruf' => 'み',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "m" kedua dalam hiragana.',
    'romaji' => 'mi',
    'jumlah_coretan' => 2,
    'kategori' => 'konsonan',
    'groups' => 'ma',
    'audio' => null,
    'catatan' => null,
    'urutan' => 32,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-MU',
    'huruf' => 'む',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "m" ketiga dalam hiragana.',
    'romaji' => 'mu',
    'jumlah_coretan' => 3,
    'kategori' => 'konsonan',
    'groups' => 'ma',
    'audio' => null,
    'catatan' => null,
    'urutan' => 33,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-ME',
    'huruf' => 'め',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "m" keempat dalam hiragana.',
    'romaji' => 'me',
    'jumlah_coretan' => 2,
    'kategori' => 'konsonan',
    'groups' => 'ma',
    'audio' => null,
    'catatan' => null,
    'urutan' => 34,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-MO',
    'huruf' => 'も',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf konsonan "m" terakhir dalam hiragana.',
    'romaji' => 'mo',
    'jumlah_coretan' => 3,
    'kategori' => 'konsonan',
    'groups' => 'ma',
    'audio' => null,
    'catatan' => null,
    'urutan' => 35,
    'created_at' => $now,
    'updated_at' => $now,
],
// end ma groups
          

            // ya groups
[
    'id' => 'H-GO-YA',
    'huruf' => 'や',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf pertama dari ya-gyō dalam hiragana.',
    'romaji' => 'ya',
    'jumlah_coretan' => 3,
    'kategori' => 'konsonan',
    'groups' => 'ya',
    'audio' => null,
    'catatan' => null,
    'urutan' => 36,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-YU',
    'huruf' => 'ゆ',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf kedua dari ya-gyō dalam hiragana.',
    'romaji' => 'yu',
    'jumlah_coretan' => 2,
    'kategori' => 'konsonan',
    'groups' => 'ya',
    'audio' => null,
    'catatan' => null,
    'urutan' => 37,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-YO',
    'huruf' => 'よ',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf terakhir dari ya-gyō dalam hiragana.',
    'romaji' => 'yo',
    'jumlah_coretan' => 3,
    'kategori' => 'konsonan',
    'groups' => 'ya',
    'audio' => null,
    'catatan' => null,
    'urutan' => 38,
    'created_at' => $now,
    'updated_at' => $now,
],
// end ya groups

// ra groups
[
    'id' => 'H-GO-RA',
    'huruf' => 'ら',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf pertama dari ra-gyō dalam hiragana.',
    'romaji' => 'ra',
    'jumlah_coretan' => 2,
    'kategori' => 'konsonan',
    'groups' => 'ra',
    'audio' => null,
    'catatan' => null,
    'urutan' => 39,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-RI',
    'huruf' => 'り',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf kedua dari ra-gyō dalam hiragana.',
    'romaji' => 'ri',
    'jumlah_coretan' => 2,
    'kategori' => 'konsonan',
    'groups' => 'ra',
    'audio' => null,
    'catatan' => null,
    'urutan' => 40,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-RU',
    'huruf' => 'る',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf ketiga dari ra-gyō dalam hiragana.',
    'romaji' => 'ru',
    'jumlah_coretan' => 1,
    'kategori' => 'konsonan',
    'groups' => 'ra',
    'audio' => null,
    'catatan' => null,
    'urutan' => 41,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-RE',
    'huruf' => 'れ',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf keempat dari ra-gyō dalam hiragana.',
    'romaji' => 're',
    'jumlah_coretan' => 1,
    'kategori' => 'konsonan',
    'groups' => 'ra',
    'audio' => null,
    'catatan' => null,
    'urutan' => 42,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-RO',
    'huruf' => 'ろ',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf terakhir dari ra-gyō dalam hiragana.',
    'romaji' => 'ro',
    'jumlah_coretan' => 1,
    'kategori' => 'konsonan',
    'groups' => 'ra',
    'audio' => null,
    'catatan' => null,
    'urutan' => 43,
    'created_at' => $now,
    'updated_at' => $now,
],
// end ra groups

// wa groups
[
    'id' => 'H-GO-WA',
    'huruf' => 'わ',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf pertama dari wa-gyō dalam hiragana.',
    'romaji' => 'wa',
    'jumlah_coretan' => 2,
    'kategori' => 'konsonan',
    'groups' => 'wa',
    'audio' => null,
    'catatan' => null,
    'urutan' => 44,
    'created_at' => $now,
    'updated_at' => $now,
],
[
    'id' => 'H-GO-WO',
    'huruf' => 'を',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf kedua dari wa-gyō dalam hiragana, biasanya dibaca sebagai "o" dan digunakan sebagai partikel.',
    'romaji' => 'wo',
    'jumlah_coretan' => 3,
    'kategori' => 'konsonan',
    'groups' => 'wa',
    'audio' => null,
    'catatan' => 'Meski dibaca "o", tetap ditulis "wo" dalam romaji.',
    'urutan' => 45,
    'created_at' => $now,
    'updated_at' => $now,
],
// end wa groups

// n groups
[
    'id' => 'H-GO-N',
    'huruf' => 'ん',
    'jenis_huruf' => 'hiragana',
    'kategori_huruf' => 'gojuon',
    'deskripsi' => 'Huruf nasal dalam hiragana, berdiri sendiri dan tidak termasuk dalam kelompok gojuon manapun.',
    'romaji' => 'n',
    'jumlah_coretan' => 1,
    'kategori' => 'konsonan',
    'groups' => 'n',
    'audio' => null,
    'catatan' => 'Huruf nasal yang unik dalam bahasa Jepang.',
    'urutan' => 46,
    'created_at' => $now,
    'updated_at' => $now,
],
// end n groups

         

            
        ]);
    }
}
