<?php

namespace Database\Seeders;

use App\Models\Huruf;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class HurufSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('hurufs')->insert([
            /*=================== HiRAGANA GOJUON START =================== */
            //a groups
            [
                'id' => 'H-GO-A',
                'huruf' => 'あ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'あ adalah huruf vokal dasar yang sering digunakan dalam kata-kata sederhana seperti sapaan dan nama. Dilafalkan seperti "a" pada kata "anak".',
                'romaji' => 'a',
                'jumlah_coretan' => 3,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748774537/52_tjmkqe.wav',
                'catatan' => 'Huruf dasar yang sering muncul di awal belajar bahasa Jepang.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-I',
                'huruf' => 'い',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'い biasa ditemukan dalam kata sapaan seperti いえ (rumah) atau いぬ (anjing). Dilafalkan seperti "i" dalam "ibu".',
                'romaji' => 'i',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748774571/52_1_tk3gw0.wav',
                'catatan' => 'Bentuknya sederhana dan mudah diingat.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-U',
                'huruf' => 'う',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'う digunakan dalam banyak kata kerja dan juga untuk memanjangkan bunyi vokal. Pelafalannya seperti "u" pada kata "ular".',
                'romaji' => 'u',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748776447/53_1_lb67yt.wav',
                'catatan' => 'Huruf ini sering digunakan untuk memanjangkan bunyi vokal.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-E',
                'huruf' => 'え',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'え sering muncul dalam kata benda atau sapaan seperti えき (stasiun). Dilafalkan seperti "e" dalam "enak".',
                'romaji' => 'e',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748774751/52_2_razo63.wav',
                'catatan' => 'Salah satu huruf vokal dasar yang penting dikuasai.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-O',
                'huruf' => 'お',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'お sering dipakai dalam kata-kata sopan seperti おはよう (selamat pagi). Diucapkan seperti "o" dalam "orang".',
                'romaji' => 'o',
                'jumlah_coretan' => 3,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748774874/52_3_pwsr09.wav',
                'catatan' => 'Huruf penting yang sering digunakan dalam sapaan bahasa Jepang.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end a groups

            //ka groups
            [
                'id' => 'H-GO-KA',
                'huruf' => 'か',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'か adalah huruf konsonan dengan bunyi "ka", sering digunakan dalam kosakata dasar seperti benda dan tempat.',
                'romaji' => 'ka',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ka',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748775051/52_xlwkfb.wav',
                'catatan' => 'Termasuk dalam kelompok konsonan "k". Pelafalannya mirip dengan "ka" pada kata "kaki".',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-KI',
                'huruf' => 'き',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'き adalah huruf yang mewakili bunyi "ki", sering muncul dalam kata sifat dan benda.',
                'romaji' => 'ki',
                'jumlah_coretan' => 4,
                'kategori' => 'konsonan',
                'groups' => 'ka',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748775088/52_1_qdvflo.wav',
                'catatan' => 'Huruf ini punya bentuk khas yang sering dipakai dalam kata sifat.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-KU',
                'huruf' => 'く',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'く merupakan huruf dengan bunyi "ku", bentuknya simpel dan sering dijumpai dalam kata kerja.',
                'romaji' => 'ku',
                'jumlah_coretan' => 1,
                'kategori' => 'konsonan',
                'groups' => 'ka',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748775123/52_2_nrfhy5.wav',
                'catatan' => 'Termasuk huruf dengan satu coretan yang mudah ditulis.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-KE',
                'huruf' => 'け',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'け melambangkan bunyi "ke" dan sering digunakan dalam nama orang dan tempat.',
                'romaji' => 'ke',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ka',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748775158/52_3_aggmko.wav',
                'catatan' => 'Bentuknya menyerupai angka 7 dengan tambahan coretan.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-KO',
                'huruf' => 'こ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'こ adalah huruf yang mewakili bunyi "ko", sering digunakan dalam kata tunjuk dan nama.',
                'romaji' => 'ko',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ka',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748775194/52_4_xwpfav.wav',
                'catatan' => 'Bentuknya sederhana dan mudah dikenali pemula.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end ka groups

            //sa groups
            [
                'id' => 'H-GO-SA',
                'huruf' => 'さ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "s" pertama dalam hiragana.',
                'romaji' => 'sa',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-SHI',
                'huruf' => 'し',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "s" kedua dalam hiragana. Dibaca "shi", bukan "si".',
                'romaji' => 'shi',
                'jumlah_coretan' => 1,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-SU',
                'huruf' => 'す',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "s" ketiga dalam hiragana.',
                'romaji' => 'su',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-SE',
                'huruf' => 'せ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "s" keempat dalam hiragana.',
                'romaji' => 'se',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-SO',
                'huruf' => 'そ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "s" kelima dalam hiragana.',
                'romaji' => 'so',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end sa groups

            //ta groups
            [
                'id' => 'H-GO-TA',
                'huruf' => 'た',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "t" pertama dalam hiragana.',
                'romaji' => 'ta',
                'jumlah_coretan' => 4,
                'kategori' => 'konsonan',
                'groups' => 'ta',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-CHI',
                'huruf' => 'ち',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "ch" dalam hiragana.',
                'romaji' => 'chi',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ta',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-TSU',
                'huruf' => 'つ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "ts" dalam hiragana.',
                'romaji' => 'tsu',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ta',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-TE',
                'huruf' => 'て',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "t" kedua dalam hiragana.',
                'romaji' => 'te',
                'jumlah_coretan' => 1,
                'kategori' => 'konsonan',
                'groups' => 'ta',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-TO',
                'huruf' => 'と',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "t" terakhir dalam hiragana.',
                'romaji' => 'to',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ta',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end ta groups

            //na groups
            [
                'id' => 'H-GO-NA',
                'huruf' => 'な',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "n" pertama dalam hiragana.',
                'romaji' => 'na',
                'jumlah_coretan' => 4,
                'kategori' => 'konsonan',
                'groups' => 'na',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-NI',
                'huruf' => 'に',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "n" kedua dalam hiragana.',
                'romaji' => 'ni',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'na',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-NU',
                'huruf' => 'ぬ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "n" ketiga dalam hiragana.',
                'romaji' => 'nu',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'na',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-NE',
                'huruf' => 'ね',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "n" keempat dalam hiragana.',
                'romaji' => 'ne',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'na',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-NO',
                'huruf' => 'の',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "n" terakhir dalam hiragana.',
                'romaji' => 'no',
                'jumlah_coretan' => 1,
                'kategori' => 'konsonan',
                'groups' => 'na',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end na groups

            //ha groups
            [
                'id' => 'H-GO-HA',
                'huruf' => 'は',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "h" pertama dalam hiragana.',
                'romaji' => 'ha',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ha',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-HI',
                'huruf' => 'ひ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "h" kedua dalam hiragana.',
                'romaji' => 'hi',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ha',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-FU',
                'huruf' => 'ふ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "f" dalam hiragana, dibaca "fu".',
                'romaji' => 'fu',
                'jumlah_coretan' => 1,
                'kategori' => 'konsonan',
                'groups' => 'ha',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-HE',
                'huruf' => 'へ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "h" keempat dalam hiragana.',
                'romaji' => 'he',
                'jumlah_coretan' => 1,
                'kategori' => 'konsonan',
                'groups' => 'ha',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-HO',
                'huruf' => 'ほ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "h" terakhir dalam hiragana.',
                'romaji' => 'ho',
                'jumlah_coretan' => 4,
                'kategori' => 'konsonan',
                'groups' => 'ha',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end ha groups

            //ma groups
            [
                'id' => 'H-GO-MA',
                'huruf' => 'ま',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "m" pertama dalam hiragana.',
                'romaji' => 'ma',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ma',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-MI',
                'huruf' => 'み',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "m" kedua dalam hiragana.',
                'romaji' => 'mi',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ma',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-MU',
                'huruf' => 'む',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "m" ketiga dalam hiragana.',
                'romaji' => 'mu',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ma',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-ME',
                'huruf' => 'め',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "m" keempat dalam hiragana.',
                'romaji' => 'me',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ma',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-MO',
                'huruf' => 'も',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "m" terakhir dalam hiragana.',
                'romaji' => 'mo',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ma',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end ma groups

            //ya groups
            [
                'id' => 'H-GO-YA',
                'huruf' => 'や',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf pertama dari ya-gyō dalam hiragana.',
                'romaji' => 'ya',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ya',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-YU',
                'huruf' => 'ゆ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf kedua dari ya-gyō dalam hiragana.',
                'romaji' => 'yu',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ya',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-YO',
                'huruf' => 'よ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf terakhir dari ya-gyō dalam hiragana.',
                'romaji' => 'yo',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ya',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end ya groups

            //ra groups
            [
                'id' => 'H-GO-RA',
                'huruf' => 'ら',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf pertama dari ra-gyō dalam hiragana.',
                'romaji' => 'ra',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ra',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-RI',
                'huruf' => 'り',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf kedua dari ra-gyō dalam hiragana.',
                'romaji' => 'ri',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ra',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-RU',
                'huruf' => 'る',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf ketiga dari ra-gyō dalam hiragana.',
                'romaji' => 'ru',
                'jumlah_coretan' => 1,
                'kategori' => 'konsonan',
                'groups' => 'ra',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-RE',
                'huruf' => 'れ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf keempat dari ra-gyō dalam hiragana.',
                'romaji' => 're',
                'jumlah_coretan' => 1,
                'kategori' => 'konsonan',
                'groups' => 'ra',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-RO',
                'huruf' => 'ろ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf terakhir dari ra-gyō dalam hiragana.',
                'romaji' => 'ro',
                'jumlah_coretan' => 1,
                'kategori' => 'konsonan',
                'groups' => 'ra',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end ra groups

            // wa groups
            [
                'id' => 'H-GO-WA',
                'huruf' => 'わ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf pertama dari wa-gyō dalam hiragana.',
                'romaji' => 'wa',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'wa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-WO',
                'huruf' => 'を',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf kedua dari wa-gyō dalam hiragana, biasanya dibaca sebagai "o" dan digunakan sebagai partikel.',
                'romaji' => 'wo',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'wa',
                'audio' => null,
                'catatan' => 'Meski dibaca "o", tetap ditulis "wo" dalam romaji.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end wa groups

            //n groups
            [
                'id' => 'H-GO-N',
                'huruf' => 'ん',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf nasal dalam hiragana, berdiri sendiri dan tidak termasuk dalam kelompok gojuon manapun.',
                'romaji' => 'n',
                'jumlah_coretan' => 1,
                'kategori' => 'konsonan',
                'groups' => 'n',
                'audio' => null,
                'catatan' => 'Huruf nasal yang unik dalam bahasa Jepang.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end n groups

            /*=================== HiRAGANA GOJUON END =================== */

            /*=================== HiRAGANA DAKUTEN START =================== */
            //ga groups
            [
                'id' => 'H-DA-GA',
                'huruf' => 'が',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Huruf "ga" dalam hiragana dengan tanda dakuten.',
                'romaji' => 'ga',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ga',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-DA-GI',
                'huruf' => 'ぎ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Huruf "gi" dalam hiragana dengan tanda dakuten.',
                'romaji' => 'gi',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ga',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-DA-GU',
                'huruf' => 'ぐ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Huruf "gu" dalam hiragana dengan tanda dakuten.',
                'romaji' => 'gu',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ga',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-DA-GE',
                'huruf' => 'げ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Huruf "ge" dalam hiragana dengan tanda dakuten.',
                'romaji' => 'ge',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ga',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-DA-GO',
                'huruf' => 'ご',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Huruf "go" dalam hiragana dengan tanda dakuten.',
                'romaji' => 'go',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ga',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end ga groups

            //za groups
            [
                'id' => 'H-DA-ZA',
                'huruf' => 'ざ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Huruf "za" dalam hiragana dengan tanda dakuten.',
                'romaji' => 'za',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'za',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-DASA-JI',
                'huruf' => 'じ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Huruf "ji" dalam hiragana dengan tanda dakuten.',
                'romaji' => 'ji',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'za',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-DASA-ZU',
                'huruf' => 'ず',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Huruf "zu" dalam hiragana dengan tanda dakuten.',
                'romaji' => 'zu',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'za',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-DA-ZE',
                'huruf' => 'ぜ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Huruf "ze" dalam hiragana dengan tanda dakuten.',
                'romaji' => 'ze',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'za',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-DA-ZO',
                'huruf' => 'ぞ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Huruf "zo" dalam hiragana dengan tanda dakuten.',
                'romaji' => 'zo',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'za',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end za groups

            //da groups
            [
                'id' => 'H-DA-DA',
                'huruf' => 'だ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Huruf "da" dalam hiragana dengan tanda dakuten.',
                'romaji' => 'da',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'da',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-DATA-JI',
                'huruf' => 'ぢ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Huruf "ji" (kadang dibaca "di") dalam hiragana dengan tanda dakuten.',
                'romaji' => 'ji',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'da',
                'audio' => null,
                'catatan' => 'Jarang digunakan dalam kata umum.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-DATA-ZU',
                'huruf' => 'づ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Huruf "zu" (kadang dibaca "du") dalam hiragana dengan tanda dakuten.',
                'romaji' => 'zu',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'da',
                'audio' => null,
                'catatan' => 'Jarang digunakan dalam kata umum.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-DA-DE',
                'huruf' => 'で',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Huruf "de" dalam hiragana dengan tanda dakuten.',
                'romaji' => 'de',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'da',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-DA-DO',
                'huruf' => 'ど',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Huruf "do" dalam hiragana dengan tanda dakuten.',
                'romaji' => 'do',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'da',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end da groups

            //ba groups
            [
                'id' => 'H-DA-BA',
                'huruf' => 'ば',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Huruf "ba" dalam hiragana dengan tanda dakuten.',
                'romaji' => 'ba',
                'jumlah_coretan' => 4,
                'kategori' => 'konsonan',
                'groups' => 'ba',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-DA-BI',
                'huruf' => 'び',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Huruf "bi" dalam hiragana dengan tanda dakuten.',
                'romaji' => 'bi',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ba',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-DA-BU',
                'huruf' => 'ぶ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Huruf "bu" dalam hiragana dengan tanda dakuten.',
                'romaji' => 'bu',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ba',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-DA-BE',
                'huruf' => 'べ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Huruf "be" dalam hiragana dengan tanda dakuten.',
                'romaji' => 'be',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ba',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-DA-BO',
                'huruf' => 'ぼ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Huruf "bo" dalam hiragana dengan tanda dakuten.',
                'romaji' => 'bo',
                'jumlah_coretan' => 4,
                'kategori' => 'konsonan',
                'groups' => 'ba',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end ba groups

            /*=================== HiRAGANA DAKUTEN END =================== */

            /*=================== HiRAGANA HADAKUTEN START =================== */
            //pa groups
            [
                'id' => 'H-HA-PA',
                'huruf' => 'ぱ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'handakuten',
                'deskripsi' => 'Huruf "pa" dalam hiragana dengan tanda handakuten.',
                'romaji' => 'pa',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'pa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-HA-PI',
                'huruf' => 'ぴ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'handakuten',
                'deskripsi' => 'Huruf "pi" dalam hiragana dengan tanda handakuten.',
                'romaji' => 'pi',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'pa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-HA-PU',
                'huruf' => 'ぷ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'handakuten',
                'deskripsi' => 'Huruf "pu" dalam hiragana dengan tanda handakuten.',
                'romaji' => 'pu',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'pa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-HA-PE',
                'huruf' => 'ぺ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'handakuten',
                'deskripsi' => 'Huruf "pe" dalam hiragana dengan tanda handakuten.',
                'romaji' => 'pe',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'pa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-HA-PO',
                'huruf' => 'ぽ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'handakuten',
                'deskripsi' => 'Huruf "po" dalam hiragana dengan tanda handakuten.',
                'romaji' => 'po',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'pa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end pa groups
            /*=================== HiRAGANA HADAKUTEN END =================== */

            /*=================== HIRAGANA YOUON START =================== */
            //ka groups
            [
                'id' => 'H-YO-KYA',
                'huruf' => 'きゃ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "kya" dalam hiragana, kombinasi huruf ka dengan ya kecil (youon).',
                'romaji' => 'kya',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ka',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-YO-KYU',
                'huruf' => 'きゅ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "kyu" dalam hiragana, kombinasi huruf ka dengan yu kecil (youon).',
                'romaji' => 'kyu',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ka',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-YO-KYO',
                'huruf' => 'きょ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "kyo" dalam hiragana, kombinasi huruf ka dengan yo kecil (youon).',
                'romaji' => 'kyo',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ka',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end ka groups

            //sa groups
            [
                'id' => 'H-YO-SHA',
                'huruf' => 'しゃ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "sha" dalam hiragana, kombinasi huruf sa dengan ya kecil (youon).',
                'romaji' => 'sha',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-YO-SHU',
                'huruf' => 'しゅ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "shu" dalam hiragana, kombinasi huruf sa dengan yu kecil (youon).',
                'romaji' => 'shu',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-YO-SHO',
                'huruf' => 'しょ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "sho" dalam hiragana, kombinasi huruf sa dengan yo kecil (youon).',
                'romaji' => 'sho',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end sa groups

            //ta groups
            [
                'id' => 'H-YO-CHA',
                'huruf' => 'ちゃ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "cha" dalam hiragana, kombinasi huruf ta dengan ya kecil (youon).',
                'romaji' => 'cha',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ta',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-YO-CHU',
                'huruf' => 'ちゅ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "chu" dalam hiragana, kombinasi huruf ta dengan yu kecil (youon).',
                'romaji' => 'chu',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ta',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-YO-CHO',
                'huruf' => 'ちょ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "cho" dalam hiragana, kombinasi huruf ta dengan yo kecil (youon).',
                'romaji' => 'cho',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ta',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end ta groups

            //na groups
            [
                'id' => 'H-YO-NYA',
                'huruf' => 'にゃ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "nya" dalam hiragana, kombinasi huruf na dengan ya kecil (youon).',
                'romaji' => 'nya',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'na',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-YO-NYU',
                'huruf' => 'にゅ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "nyu" dalam hiragana, kombinasi huruf na dengan yu kecil (youon).',
                'romaji' => 'nyu',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'na',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-YO-NYO',
                'huruf' => 'にょ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "nyo" dalam hiragana, kombinasi huruf na dengan yo kecil (youon).',
                'romaji' => 'nyo',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'na',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end na groups

            //ha groups
            [
                'id' => 'H-YO-HYA',
                'huruf' => 'ひゃ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "hya" dalam hiragana, kombinasi huruf ha dengan ya kecil (youon).',
                'romaji' => 'hya',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ha',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-YO-HYU',
                'huruf' => 'ひゅ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "hyu" dalam hiragana, kombinasi huruf ha dengan yu kecil (youon).',
                'romaji' => 'hyu',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ha',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-YO-HYO',
                'huruf' => 'ひょ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "hyo" dalam hiragana, kombinasi huruf ha dengan yo kecil (youon).',
                'romaji' => 'hyo',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ha',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end ha groups

            //ma groups
            [
                'id' => 'H-YO-MYA',
                'huruf' => 'みゃ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "mya" dalam hiragana, kombinasi huruf ma dengan ya kecil (youon).',
                'romaji' => 'mya',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ma',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-YO-MYU',
                'huruf' => 'みゅ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "myu" dalam hiragana, kombinasi huruf ma dengan yu kecil (youon).',
                'romaji' => 'myu',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ma',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-YO-MYO',
                'huruf' => 'みょ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "myo" dalam hiragana, kombinasi huruf ma dengan yo kecil (youon).',
                'romaji' => 'myo',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ma',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end ma groups

            //ra groups
            [
                'id' => 'H-YO-RYA',
                'huruf' => 'りゃ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "rya" dalam hiragana, kombinasi huruf ra dengan ya kecil (youon).',
                'romaji' => 'rya',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ra',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-YO-RYU',
                'huruf' => 'りゅ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "ryu" dalam hiragana, kombinasi huruf ra dengan yu kecil (youon).',
                'romaji' => 'ryu',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ra',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-YO-RYO',
                'huruf' => 'りょ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'youon',
                'deskripsi' => 'Huruf "ryo" dalam hiragana, kombinasi huruf ra dengan yo kecil (youon).',
                'romaji' => 'ryo',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ra',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end ra groups            
            
            /* =================== HIRAGANA YOUON END =================== */

            /*=================== HIRAGANA SOKUON START =================== */
            [
                'id' => 'H-SOKUON',
                'huruf' => 'っ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'sokuon',
                'deskripsi' => 'Huruf sokuon kecil dalam hiragana, digunakan untuk penekanan konsonan berikutnya (double consonant).',
                'romaji' => '',
                'jumlah_coretan' => 1,
                'kategori' => 'spesial',
                'groups' => 'sokuon',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            /*=================== HIRAGANA SOKUON END =================== */
            
            //=================== hiragana choon start ===================
            [
                'id' => 'H-CHO-KAA',
                'huruf' => 'かあ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'choon',
                'deskripsi' => 'Vokal panjang dengan mengulang huruf "a" menjadi "kaa".',
                'romaji' => 'kaa',
                'jumlah_coretan' => 3,
                'kategori' => 'vokal panjang',
                'groups' => 'choon',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-CHO-KII',
                'huruf' => 'きい',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'choon',
                'deskripsi' => 'Vokal panjang dengan mengulang huruf "i" menjadi "kii".',
                'romaji' => 'kii',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal panjang',
                'groups' => 'choon',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-CHO-KUU',
                'huruf' => 'くう',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'choon',
                'deskripsi' => 'Vokal panjang dengan mengulang huruf "u" menjadi "kuu".',
                'romaji' => 'kuu',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal panjang',
                'groups' => 'choon',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-CHO-SEE',
                'huruf' => 'せえ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'choon',
                'deskripsi' => 'Vokal panjang dengan mengulang huruf "e" menjadi "see".',
                'romaji' => 'see',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal panjang',
                'groups' => 'choon',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-CHO-TOO',
                'huruf' => 'とお',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'choon',
                'deskripsi' => 'Vokal panjang dengan mengulang huruf "o" menjadi "too".',
                'romaji' => 'too',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal panjang',
                'groups' => 'choon',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //=================== hiragana choon end ===================

            /*=================== KATAKANA GOJUON START =================== */

            //a groups
            [
                'id' => 'K-GO-A',
                'huruf' => 'ア',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf vokal "a" dalam katakana.',
                'romaji' => 'a',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-I',
                'huruf' => 'イ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf vokal "i" dalam katakana.',
                'romaji' => 'i',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-U',
                'huruf' => 'ウ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf vokal "u" dalam katakana.',
                'romaji' => 'u',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-E',
                'huruf' => 'エ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf vokal "e" dalam katakana.',
                'romaji' => 'e',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-O',
                'huruf' => 'オ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf vokal "o" dalam katakana.',
                'romaji' => 'o',
                'jumlah_coretan' => 3,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end o groups

            //ka groups
            [
                'id' => 'K-GO-KA',
                'huruf' => 'ア',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf vokal "a" dalam katakana.',
                'romaji' => 'a',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-KI',
                'huruf' => 'イ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf vokal "i" dalam katakana.',
                'romaji' => 'i',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-KU',
                'huruf' => 'ウ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf vokal "u" dalam katakana.',
                'romaji' => 'u',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-KE',
                'huruf' => 'エ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf vokal "e" dalam katakana.',
                'romaji' => 'e',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-KO',
                'huruf' => 'オ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf vokal "o" dalam katakana.',
                'romaji' => 'o',
                'jumlah_coretan' => 3,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end ka groups

            //sa groups
            [
                'id' => 'K-GO-SA',
                'huruf' => 'サ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "s" pertama dengan vokal "a" dalam katakana.',
                'romaji' => 'sa',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-SHI',
                'huruf' => 'シ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "s" dengan vokal "i" dalam katakana.',
                'romaji' => 'shi',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-SU',
                'huruf' => 'ス',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "s" dengan vokal "u" dalam katakana.',
                'romaji' => 'su',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-SE',
                'huruf' => 'セ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "s" dengan vokal "e" dalam katakana.',
                'romaji' => 'se',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-SO',
                'huruf' => 'ソ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "s" dengan vokal "o" dalam katakana.',
                'romaji' => 'so',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end sa groups

            //ta groups
            [
                'id' => 'K-GO-TA',
                'huruf' => 'タ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "t" pertama dengan vokal "a" dalam katakana.',
                'romaji' => 'ta',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ta',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-CHI',
                'huruf' => 'チ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "t" dengan vokal "i" dalam katakana, dilafalkan "chi".',
                'romaji' => 'chi',
                'jumlah_coretan' => 4,
                'kategori' => 'konsonan',
                'groups' => 'ta',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-TSU',
                'huruf' => 'ツ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "t" dengan vokal "u" dalam katakana, dilafalkan "tsu".',
                'romaji' => 'tsu',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ta',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-TE',
                'huruf' => 'テ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "t" dengan vokal "e" dalam katakana.',
                'romaji' => 'te',
                'jumlah_coretan' => 4,
                'kategori' => 'konsonan',
                'groups' => 'ta',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-TO',
                'huruf' => 'ト',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "t" dengan vokal "o" dalam katakana.',
                'romaji' => 'to',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ta',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end ta groups

            //na groups
            [
                'id' => 'K-GO-NA',
                'huruf' => 'ナ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "n" pertama dengan vokal "a" dalam katakana.',
                'romaji' => 'na',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'na',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-NI',
                'huruf' => 'ニ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "n" dengan vokal "i" dalam katakana.',
                'romaji' => 'ni',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'na',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-NU',
                'huruf' => 'ヌ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "n" dengan vokal "u" dalam katakana.',
                'romaji' => 'nu',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'na',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-NE',
                'huruf' => 'ネ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "n" dengan vokal "e" dalam katakana.',
                'romaji' => 'ne',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'na',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-NO',
                'huruf' => 'ノ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "n" dengan vokal "o" dalam katakana.',
                'romaji' => 'no',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'na',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end na groups

            //ha groups
            [
                'id' => 'K-GO-HA',
                'huruf' => 'ハ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "h" pertama dengan vokal "a" dalam katakana.',
                'romaji' => 'ha',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ha',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-HI',
                'huruf' => 'ヒ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "h" dengan vokal "i" dalam katakana.',
                'romaji' => 'hi',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ha',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-FU',
                'huruf' => 'フ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "h" dengan vokal "u" dalam katakana, dilafalkan "fu".',
                'romaji' => 'fu',
                'jumlah_coretan' => 4,
                'kategori' => 'konsonan',
                'groups' => 'ha',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-HE',
                'huruf' => 'ヘ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "h" dengan vokal "e" dalam katakana.',
                'romaji' => 'he',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ha',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-HO',
                'huruf' => 'ホ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "h" dengan vokal "o" dalam katakana.',
                'romaji' => 'ho',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ha',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end ha groups

            //ma groups
            [
                'id' => 'K-GO-MA',
                'huruf' => 'マ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "m" pertama dengan vokal "a" dalam katakana.',
                'romaji' => 'ma',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ma',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-MI',
                'huruf' => 'ミ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "m" dengan vokal "i" dalam katakana.',
                'romaji' => 'mi',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ma',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-MU',
                'huruf' => 'ム',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "m" dengan vokal "u" dalam katakana.',
                'romaji' => 'mu',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ma',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-ME',
                'huruf' => 'メ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "m" dengan vokal "e" dalam katakana.',
                'romaji' => 'me',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ma',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-MO',
                'huruf' => 'モ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "m" dengan vokal "o" dalam katakana.',
                'romaji' => 'mo',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ma',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end ma groups

            //ya groups
            [
                'id' => 'K-GO-YA',
                'huruf' => 'ヤ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "y" pertama dengan vokal "a" dalam katakana.',
                'romaji' => 'ya',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ya',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-YU',
                'huruf' => 'ユ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "y" dengan vokal "u" dalam katakana.',
                'romaji' => 'yu',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ya',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-YO',
                'huruf' => 'ヨ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "y" dengan vokal "o" dalam katakana.',
                'romaji' => 'yo',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ya',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end ya groups

            //ra groups
            [
                'id' => 'K-GO-RA',
                'huruf' => 'ラ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "r" pertama dengan vokal "a" dalam katakana.',
                'romaji' => 'ra',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ra',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-RI',
                'huruf' => 'リ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "r" dengan vokal "i" dalam katakana.',
                'romaji' => 'ri',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ra',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-RU',
                'huruf' => 'ル',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "r" dengan vokal "u" dalam katakana.',
                'romaji' => 'ru',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ra',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-RE',
                'huruf' => 'レ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "r" dengan vokal "e" dalam katakana.',
                'romaji' => 're',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ra',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-RO',
                'huruf' => 'ロ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "r" dengan vokal "o" dalam katakana.',
                'romaji' => 'ro',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ra',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end ra groups

            //wa groups
            [
                'id' => 'K-GO-WA',
                'huruf' => 'ワ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "w" pertama dengan vokal "a" dalam katakana.',
                'romaji' => 'wa',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'wa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-WO',
                'huruf' => 'ヲ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "w" dengan vokal "o" dalam katakana.',
                'romaji' => 'wo',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'wa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end wa groups

            //n groups
            [
                'id' => 'K-GO-N',
                'huruf' => 'ン',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf nasal yang merupakan satu-satunya konsonan tanpa vokal dalam katakana.',
                'romaji' => 'n',
                'jumlah_coretan' => 1,
                'kategori' => 'konsonan',
                'groups' => 'n',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //end n groups
            
            
            /*=================== KATAKANA GOJUON END =================== */
        
        ]);
    }
}
