<?php

namespace Database\Seeders;

use App\Models\Huruf;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class HurufSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('hurufs')->insert([
            // Hiragana - Gojuon
            [
                'id' => 'H-GO-A',
                'huruf' => 'あ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'あ adalah huruf vokal dasar yang sering digunakan dalam kata-kata sederhana seperti sapaan dan nama. Dilafalkan seperti "a" pada kata "anak".',
                'romaji' => 'a',
                'jumlah_coretan' => 3,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748774537/52_tjmkqe.wav',
                'catatan' => 'Huruf dasar yang sering muncul di awal belajar bahasa Jepang.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-I',
                'huruf' => 'い',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'い biasa ditemukan dalam kata sapaan seperti いえ (rumah) atau いぬ (anjing). Dilafalkan seperti "i" dalam "ibu".',
                'romaji' => 'i',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748774571/52_1_tk3gw0.wav',
                'catatan' => 'Bentuknya sederhana dan mudah diingat.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-U',
                'huruf' => 'う',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'う digunakan dalam banyak kata kerja dan juga untuk memanjangkan bunyi vokal. Pelafalannya seperti "u" pada kata "ular".',
                'romaji' => 'u',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748776447/53_1_lb67yt.wav',
                'catatan' => 'Huruf ini sering digunakan untuk memanjangkan bunyi vokal.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-E',
                'huruf' => 'え',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'え sering muncul dalam kata benda atau sapaan seperti えき (stasiun). Dilafalkan seperti "e" dalam "enak".',
                'romaji' => 'e',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748774751/52_2_razo63.wav',
                'catatan' => 'Salah satu huruf vokal dasar yang penting dikuasai.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-O',
                'huruf' => 'お',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'お sering dipakai dalam kata-kata sopan seperti おはよう (selamat pagi). Diucapkan seperti "o" dalam "orang".',
                'romaji' => 'o',
                'jumlah_coretan' => 3,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748774874/52_3_pwsr09.wav',
                'catatan' => 'Huruf penting yang sering digunakan dalam sapaan bahasa Jepang.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-KA',
                'huruf' => 'か',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'か adalah huruf konsonan dengan bunyi "ka", sering digunakan dalam kosakata dasar seperti benda dan tempat.',
                'romaji' => 'ka',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ka',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748775051/52_xlwkfb.wav',
                'catatan' => 'Termasuk dalam kelompok konsonan "k". Pelafalannya mirip dengan "ka" pada kata "kaki".',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-KI',
                'huruf' => 'き',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'き adalah huruf yang mewakili bunyi "ki", sering muncul dalam kata sifat dan benda.',
                'romaji' => 'ki',
                'jumlah_coretan' => 4,
                'kategori' => 'konsonan',
                'groups' => 'ka',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748775088/52_1_qdvflo.wav',
                'catatan' => 'Huruf ini punya bentuk khas yang sering dipakai dalam kata sifat.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-KU',
                'huruf' => 'く',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'く merupakan huruf dengan bunyi "ku", bentuknya simpel dan sering dijumpai dalam kata kerja.',
                'romaji' => 'ku',
                'jumlah_coretan' => 1,
                'kategori' => 'konsonan',
                'groups' => 'ka',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748775123/52_2_nrfhy5.wav',
                'catatan' => 'Termasuk huruf dengan satu coretan yang mudah ditulis.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-KE',
                'huruf' => 'け',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'け melambangkan bunyi "ke" dan sering digunakan dalam nama orang dan tempat.',
                'romaji' => 'ke',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ka',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748775158/52_3_aggmko.wav',
                'catatan' => 'Bentuknya menyerupai angka 7 dengan tambahan coretan.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-KO',
                'huruf' => 'こ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'こ adalah huruf yang mewakili bunyi "ko", sering digunakan dalam kata tunjuk dan nama.',
                'romaji' => 'ko',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ka',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1748775194/52_4_xwpfav.wav',
                'catatan' => 'Bentuknya sederhana dan mudah dikenali pemula.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // hiragana no sound
            
            [
                'id' => 'H-GO-SA',
                'huruf' => 'さ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "s" pertama dalam hiragana.',
                'romaji' => 'sa',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-SHI',
                'huruf' => 'し',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "s" kedua dalam hiragana. Dibaca "shi", bukan "si".',
                'romaji' => 'shi',
                'jumlah_coretan' => 1,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-SU',
                'huruf' => 'す',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "s" ketiga dalam hiragana.',
                'romaji' => 'su',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-SE',
                'huruf' => 'せ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "s" keempat dalam hiragana.',
                'romaji' => 'se',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-SO',
                'huruf' => 'そ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "s" kelima dalam hiragana.',
                'romaji' => 'so',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
         
            // Hiragana - Dakuten
            [
                'id' => 'H-DA-GA',
                'huruf' => 'が',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Bersuara dari "ka", digunakan dalam kata benda.',
                'romaji' => 'ga',
                'jumlah_coretan' => 3,
                'kategori' => 'non vokal',
                'groups' => 'ga',
                'catatan' => null,
                'audio' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-DA-GI',
                'huruf' => 'ぎ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Bersuara dari "ki".',
                'romaji' => 'gi',
                'jumlah_coretan' => 3,
                'kategori' => 'non vokal',
                'groups' => 'ga',
                'catatan' => null,
                'audio' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-DA-GU',
                'huruf' => 'ぐ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Bersuara dari "ku".',
                'romaji' => 'gu',
                'jumlah_coretan' => 3,
                'kategori' => 'non vokal',
                'groups' => 'ga',
                'catatan' => null,
                'audio' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Katakana - Gojuon
            [
                'id' => 'K-GO-A',
                'huruf' => 'ア',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf vokal pertama dalam katakana.',
                'romaji' => 'a',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal',
                'groups' => 'a',
                'catatan' => null,
                'audio' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-KA',
                'huruf' => 'カ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "ka" dalam katakana.',
                'romaji' => 'ka',
                'jumlah_coretan' => 2,
                'kategori' => 'non vokal',
                'groups' => 'ka',
                'catatan' => null,
                'audio' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-SA',
                'huruf' => 'サ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "sa" dalam katakana.',
                'romaji' => 'sa',
                'jumlah_coretan' => 2,
                'kategori' => 'non vokal',
                'groups' => 'sa',
                'catatan' => null,
                'audio' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Katakana - Handakuten
            [
                'id' => 'K-HA-PA',
                'huruf' => 'パ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'handakuten',
                'deskripsi' => 'Bersuara dari "ha" menggunakan simbol lingkaran kecil.',
                'romaji' => 'pa',
                'jumlah_coretan' => 2,
                'kategori' => 'non vokal',
                'groups' => 'pa',
                'catatan' => null,
                'audio' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-HA-PI',
                'huruf' => 'ピ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'handakuten',
                'deskripsi' => 'Bersuara dari "hi" menggunakan simbol lingkaran kecil.',
                'romaji' => 'pi',
                'jumlah_coretan' => 2,
                'kategori' => 'non vokal',
                'groups' => 'pa',
                'catatan' => null,
                'audio' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-HA-PU',
                'huruf' => 'プ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'handakuten',
                'deskripsi' => 'Bersuara dari "fu" (hu) menggunakan simbol lingkaran kecil.',
                'romaji' => 'pu',
                'jumlah_coretan' => 2,
                'kategori' => 'non vokal',
                'groups' => 'pa',
                'catatan' => null,
                'audio' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
