<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\SoalKosakata;
use App\Models\Kosakata;
use Illuminate\Support\Facades\DB;

class SoalKosakataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

          $soalkosakata = [
             //watashi
            [
                'kosakata_id' => 'KOSA-001',
                'level' => 'intermediate',
                'soal_kanji' => '____ は学生です。',
                'soal_furigana' => '____ はがくせいです。',
                'soal_romaji' => '____ wa gakusei desu.',
                'soal_arti' => '____ adalah pelajar.',
                'opsi_a_kanji' => '日本語',
                'opsi_a_furigana' => 'にほんご',
                'opsi_a_romaji' => 'nihongo',
                'opsi_a_arti' => 'Bahasa Jepang',
                'opsi_b_kanji' => '猫',
                'opsi_b_furigana' => 'ねこ',
                'opsi_b_romaji' => 'neko',
                'opsi_b_arti' => 'kucing',
                'opsi_c_kanji' => '本',
                'opsi_c_furigana' => 'ほん',
                'opsi_c_romaji' => 'hon',
                'opsi_c_arti' => 'buku',
                'opsi_d_kanji' => '私',
                'opsi_d_furigana' => 'わたし',
                'opsi_d_romaji' => 'watashi',
                'opsi_d_arti' => 'saya',
                'jawaban_benar' => 'd',
            ],
             [
                'kosakata_id' => 'KOSA-001',
                'level' => 'advanced',
                'soal_kanji' => '',
                'soal_furigana' => '',
                'soal_romaji' => '',
                'soal_arti' => 'Pilih kalimat yang paling natural untuk penggunaan kosakata 私 (わたし)',
                'opsi_a_kanji' => '私は学生です。',
                'opsi_a_furigana' => 'わたしは がくせいです',
                'opsi_a_romaji' => 'Watashi wa gakusei desu.',
                'opsi_a_arti' => 'Saya adalah mahasiswa.',
                'opsi_b_kanji' => 'リンゴは私です。',
                'opsi_b_furigana' => 'りんごは わたしです。',
                'opsi_b_romaji' => 'Ringo wa watashi desu.',
                'opsi_b_arti' => 'Apel adalah saya',
                'opsi_c_kanji' => '私車を食べます。',
                'opsi_c_furigana' => 'わたし くるまを たべます。',
                'opsi_c_romaji' => 'Watashi kuruma o tabemasu.',
                'opsi_c_arti' => 'Saya mobil makan.',
                'opsi_d_kanji' => '私時計が走ります。',
                'opsi_d_furigana' => 'わたし とけいが はしります。',
                'opsi_d_romaji' => 'Watashi tokei ga hashirimasu.',
                'opsi_d_arti' => 'Saya jam berlari. ',
                'jawaban_benar' => 'a',
            ],
            //end watashi

            //arigatou
             [
                'kosakata_id' => 'KOSA-002',
                'level' => 'intermediate',
                'soal_kanji' => 'さっきは助けてくれて____。',
                'soal_furigana' => 'さっきは たすけてくれて____。',
                'soal_romaji' => 'Sakki wa tasukete kurete ____.',
                'soal_arti' => 'tadi ____ karena sudah menolong saya.',
                'opsi_a_kanji' => '謝る',
                'opsi_a_furigana' => 'あやまる',
                'opsi_a_romaji' => 'ayamaru',
                'opsi_a_arti' => 'minta maaf',
                'opsi_b_kanji' => '泣く',
                'opsi_b_furigana' => 'なく',
                'opsi_b_romaji' => 'naku',
                'opsi_b_arti' => 'menangis',
                'opsi_c_kanji' => 'ありがとうございます',
                'opsi_c_furigana' => 'ありがとうございます',
                'opsi_c_romaji' => 'arigatou gozaimasu',
                'opsi_c_arti' => 'terima kasih',
                'opsi_d_kanji' => '働く',
                'opsi_d_furigana' => 'はたらく',
                'opsi_d_romaji' => ' hataraku',
                'opsi_d_arti' => 'bekerja',
                'jawaban_benar' => 'c',
            ],
            [
                'kosakata_id' => 'KOSA-002',
                'level' => 'advanced',
                'soal_kanji' => '',
                'soal_furigana' => '',
                'soal_romaji' => '',
                'soal_arti' => 'Pilih kalimat yang paling natural untuk penggunaan kosakata  ありがとうございます',
                'opsi_a_kanji' => 'ご協力ありがとうございます。。',
                'opsi_a_furigana' => 'ごきょうりょくありがとうございます',
                'opsi_a_romaji' => 'Gokyouryoku arigatou gozaimasu.',
                'opsi_a_arti' => 'Terima kasih atas kerja samanya.',
                'opsi_b_kanji' => '私はありがとうございますです。',
                'opsi_b_furigana' => 'わたしはありがとうございますです。',
                'opsi_b_romaji' => 'Watashi wa arigatou gozaimasu desu.',
                'opsi_b_arti' => 'Saya adalah terima kasih.',
                'opsi_c_kanji' => 'ありがとうございます猫が好きです。',
                'opsi_c_furigana' => 'ありがとうございます ねこがすきです。',
                'opsi_c_romaji' => 'Arigatou gozaimasu neko ga suki desu.',
                'opsi_c_arti' => 'terima kasih kucing suka. ',
                'opsi_d_kanji' => 'ありがとうございますは食べます。',
                'opsi_d_furigana' => ' ありがとうございますはたべます。',
                'opsi_d_romaji' => 'Arigatou gozaimasu wa tabemasu.',
                'opsi_d_arti' => 'Terima kasih makan.  ',
                'jawaban_benar' => 'a',
            ],
            //end arigatou

            //kore
               [
                'kosakata_id' => 'KOSA-003',
                'level' => 'intermediate',
                'soal_kanji' => '____は私の部屋です。',
                'soal_furigana' => '____は わたしの へやです。',
                'soal_romaji' => '____ wa watashi no heya desu.',
                'soal_arti' => '____ adalah kamar saya.',
                'opsi_a_kanji' => '車',
                'opsi_a_furigana' => 'くるま',
                'opsi_a_romaji' => 'kuruma',
                'opsi_a_arti' => 'mobil',
                'opsi_b_kanji' => '家',
                'opsi_b_furigana' => 'いえ',
                'opsi_b_romaji' => 'ie',
                'opsi_b_arti' => 'rumah',
                'opsi_c_kanji' => '恋人',
                'opsi_c_furigana' => 'こいびと',
                'opsi_c_romaji' => 'koibito',
                'opsi_c_arti' => 'pasangan',
                'opsi_d_kanji' => 'これ',
                'opsi_d_furigana' => 'これ',
                'opsi_d_romaji' => ' kore',
                'opsi_d_arti' => 'ini',
                'jawaban_benar' => 'd',
            ],
             [
                'kosakata_id' => 'KOSA-003',
                'level' => 'advanced',
                'soal_kanji' => '',
                'soal_furigana' => '',
                'soal_romaji' => '',
                'soal_arti' => 'Pilih kalimat yang paling natural untuk penggunaan kosakata これ',
                'opsi_a_kanji' => 'これ犬が走ります。',
                'opsi_a_furigana' => 'これ いぬが はしります。',
                'opsi_a_romaji' => ' Kore inu ga hashirimasu.',
                'opsi_a_arti' => 'TIni anjing berlari. ',
                'opsi_b_kanji' => 'これは私のペンです。',
                'opsi_b_furigana' => 'わたしはありがとうございますです。',
                'opsi_b_romaji' => 'Kore wa watashi no pen desu.',
                'opsi_b_arti' => 'Ini adalah pulpen saya.',
                'opsi_c_kanji' => '彼はこれ好きです。',
                'opsi_c_furigana' => 'かれは これすきです。',
                'opsi_c_romaji' => 'Kare wa kore suki desu.',
                'opsi_c_arti' => 'Dia ini suka.',
                'opsi_d_kanji' => 'これ食べます本。',
                'opsi_d_furigana' => 'これ たべます ほん',
                'opsi_d_romaji' => 'Kore tabemasu hon.',
                'opsi_d_arti' => 'Ini makan buku.',
                'jawaban_benar' => 'b',
            ],
            //end kore

            //sore
              [
                'kosakata_id' => 'KOSA-004',
                'level' => 'intermediate',
                'soal_kanji' => '____をシャツを取ってください。',
                'soal_furigana' => '____をシャツをとってください。',
                'soal_romaji' => '____ o shatsu o totte kudasai.',
                'soal_arti' => 'Tolong ambilkan kemeja ____',
                'opsi_a_kanji' => 'どこ',
                'opsi_a_furigana' => 'どこ',
                'opsi_a_romaji' => 'doko',
                'opsi_a_arti' => 'dimana',
                'opsi_b_kanji' => '何',
                'opsi_b_furigana' => 'なに / なん',
                'opsi_b_romaji' => 'nani / nan',
                'opsi_b_arti' => 'apa',
                'opsi_c_kanji' => 'それ',
                'opsi_c_furigana' => 'それ',
                'opsi_c_romaji' => 'sore',
                'opsi_c_arti' => 'itu',
                'opsi_d_kanji' => 'どうして',
                'opsi_d_furigana' => 'どうして',
                'opsi_d_romaji' => 'doushite',
                'opsi_d_arti' => 'mengapa',
                'jawaban_benar' => 'c',
            ],
              [
                'kosakata_id' => 'KOSA-004',
                'level' => 'advanced',
                'soal_kanji' => '',
                'soal_furigana' => '',
                'soal_romaji' => '',
                'soal_arti' => 'Pilih kalimat yang paling natural untuk penggunaan kosakata それ',
                'opsi_a_kanji' => 'それは私の傘です。',
                'opsi_a_furigana' => 'それは わたしの かさです。',
                'opsi_a_romaji' => 'Sore wa watashi no kasa desu.',
                'opsi_a_arti' => 'Itu adalah payung saya.',
                'opsi_b_kanji' => 'それ食べる猫が好きです',
                'opsi_b_furigana' => 'それ たべる ねこが すきです。',
                'opsi_b_romaji' => 'Sore taberu neko ga suki desu.',
                'opsi_b_arti' => 'Itu makan suka kucing. ',
                'opsi_c_kanji' => '私はそれ走ります毎日',
                'opsi_c_furigana' => 'わたしは それ はしります まいにち。',
                'opsi_c_romaji' => 'Watashi wa sore hashirimasu mainichi.',
                'opsi_c_arti' => 'Saya itu berlari setiap hari.',
                'opsi_d_kanji' => 'それが電話を読みます。',
                'opsi_d_furigana' => 'それが でんわを よみます。',
                'opsi_d_romaji' => 'Sore ga denwa o yomimasu.',
                'opsi_d_arti' => 'Itu membaca telepon. ',
                'jawaban_benar' => 'a',
            ],
            //end sore

            //are
             [
                'kosakata_id' => 'KOSA-005',
                'level' => 'intermediate',
                'soal_kanji' => '____ が富士山ですよ。',
                'soal_furigana' => '____ が ふじさん です よ。',
                'soal_romaji' => '____ ga Fujisan desu yo.',
                'soal_arti' => '____ adalah Gunung Fuji, loh.',
                'opsi_a_kanji' => 'あれ',
                'opsi_a_furigana' => 'あれ',
                'opsi_a_romaji' => 'are',
                'opsi_a_arti' => 'itu (sesuatu yang jauh dari pembicara dan lawan pembicara)',
                'opsi_b_kanji' => '場所',
                'opsi_b_furigana' => 'ばしょ',
                'opsi_b_romaji' => 'basho',
                'opsi_b_arti' => 'tempat',
                'opsi_c_kanji' => '水',
                'opsi_c_furigana' => 'みず',
                'opsi_c_romaji' => 'mizu',
                'opsi_c_arti' => 'air',
                'opsi_d_kanji' => '車',
                'opsi_d_furigana' => 'くるま',
                'opsi_d_romaji' => 'kuruma',
                'opsi_d_arti' => 'mobil',
                'jawaban_benar' => 'a',
            ],
             [
                'kosakata_id' => 'KOSA-005',
                'level' => 'advanced',
                'soal_kanji' => '',
                'soal_furigana' => '',
                'soal_romaji' => '',
                'soal_arti' => 'Pilih kalimat yang paling natural untuk penggunaan kosakata あれ',
                'opsi_a_kanji' => 'あれは毎朝コーヒーを飲みます。',
                'opsi_a_furigana' => ' あれは まいあさ コーヒーを のみます。',
                'opsi_a_romaji' => 'Are wa maiasa koohii o nomimasu.',
                'opsi_a_arti' => 'Itu minum kopi setiap pagi.',
                'opsi_b_kanji' => '私はあれテレビを歩きます。',
                'opsi_b_furigana' => 'わたしは あれ テレビを あるきます。',
                'opsi_b_romaji' => 'Watashi wa are terebi o arukimasu.',
                'opsi_b_arti' => 'Saya itu berjalan televisi.  ',
                'opsi_c_kanji' => 'あれ好きな犬を歌います',
                'opsi_c_furigana' => 'あれ すきな いぬを うたいます。',
                'opsi_c_romaji' => 'Are suki na inu o utaimasu.',
                'opsi_c_arti' => 'Itu menyanyi anjing kesukaan.',
                'opsi_d_kanji' => 'あれは遠くにある美しい湖です。',
                'opsi_d_furigana' => 'あれは とおくに ある うつくしい みずうみです。',
                'opsi_d_romaji' => 'Are wa tooku ni aru utsukushii mizuumi desu.',
                'opsi_d_arti' => ' Itu adalah danau yang indah di kejauhan. ',
                'jawaban_benar' => 'd',
            ],
            //end are

            //nomimasu
              [
                'kosakata_id' => 'KOSA-006',
                'level' => 'intermediate',
                'soal_kanji' => ' 彼は毎日ジュースを____。',
                'soal_furigana' => 'かれは まいにち ジュースを ____。',
                'soal_romaji' => 'Kare wa mainichi juusu o ____',
                'soal_arti' => 'Dia ____ jus setiap hari.',
                'opsi_a_kanji' => '吸います',
                'opsi_a_furigana' => 'すいます',
                'opsi_a_romaji' => 'uimasu',
                'opsi_a_arti' => 'mengisap',
                'opsi_b_kanji' => '取ります',
                'opsi_b_furigana' => 'とります',
                'opsi_b_romaji' => 'torimasu',
                'opsi_b_arti' => 'mengambil',
                'opsi_c_kanji' => '書きます',
                'opsi_c_furigana' => 'かきます',
                'opsi_c_romaji' => 'kakimasu',
                'opsi_c_arti' => 'menulis',
                'opsi_d_kanji' => '飲みます',
                'opsi_d_furigana' => 'のみます',
                'opsi_d_romaji' => 'nomimasu',
                'opsi_d_arti' => 'meminum',
                'jawaban_benar' => 'd',
            ],
              [
                'kosakata_id' => 'KOSA-006',
                'level' => 'advanced',
                'soal_kanji' => '',
                'soal_furigana' => '',
                'soal_romaji' => '',
                'soal_arti' => 'Pilih kalimat yang paling natural untuk penggunaan kosakata 飲みます(のみます)',
                'opsi_a_kanji' => '飲みます空が青いです。',
                'opsi_a_furigana' => 'のみます そらが あおいです。',
                'opsi_a_romaji' => 'Nomimasu sora ga aoi desu.',
                'opsi_a_arti' => 'Minum langit itu biru. ',
                'opsi_b_kanji' => '会議の後でお茶を飲みます。',
                'opsi_b_furigana' => 'かいぎの あとで おちゃを のみます。',
                'opsi_b_romaji' => 'Kaigi no ato de ocha o nomimasu.',
                'opsi_b_arti' => 'Saya minum teh setelah rapat.',
                'opsi_c_kanji' => '猫は飲みます音楽を聴きます。',
                'opsi_c_furigana' => 'ねこは のみます おんがくを ききます。',
                'opsi_c_romaji' => 'Neko wa nomimasu ongaku o kikimasu.',
                'opsi_c_arti' => 'Kucing minum mendengarkan musik. ',
                'opsi_d_kanji' => '彼は飲みますバスに乗ります。',
                'opsi_d_furigana' => 'かれは のみます バスに のります。',
                'opsi_d_romaji' => 'Kare wa nomimasu basu ni norimasu.',
                'opsi_d_arti' => 'Dia minum naik bus.',
                'jawaban_benar' => 'b',
            ],
            //end nomimasu

            //ikimasu
             [
                'kosakata_id' => 'KOSA-007',
                'level' => 'intermediate',
                'soal_kanji' => ' 来週東京へ____。',
                'soal_furigana' => ' らいしゅう とうきょうへ ____。',
                'soal_romaji' => 'Raishuu Toukyou e ____.',
                'soal_arti' => 'Minggu depan saya akan ____ ke Tokyo',
                'opsi_a_kanji' => '乗ります',
                'opsi_a_furigana' => 'のります',
                'opsi_a_romaji' => 'norimasu',
                'opsi_a_arti' => 'naik',
                'opsi_b_kanji' => '泳ぎます',
                'opsi_b_furigana' => 'およぎます',
                'opsi_b_romaji' => 'oyogimasu',
                'opsi_b_arti' => 'berenang',
                'opsi_c_kanji' => '行きます',
                'opsi_c_furigana' => 'いきます',
                'opsi_c_romaji' => 'ikimasu',
                'opsi_c_arti' => 'pergi',
                'opsi_d_kanji' => '跳びます',
                'opsi_d_furigana' => 'とびます',
                'opsi_d_romaji' => 'tobimasu',
                'opsi_d_arti' => 'meloncat',
                'jawaban_benar' => 'c',
            ],

             [
                'kosakata_id' => 'KOSA-007',
                'level' => 'advanced',
                'soal_kanji' => '',
                'soal_furigana' => '',
                'soal_romaji' => '',
                'soal_arti' => 'Pilih kalimat yang paling natural untuk penggunaan kosakata 行きます(いきます)',
                'opsi_a_kanji' => '行きますパンを食べます。',
                'opsi_a_furigana' => 'いきます パンを たべます。',
                'opsi_a_romaji' => 'Ikimasu pan o tabemasu.',
                'opsi_a_arti' => 'Pergi makan roti',
                'opsi_b_kanji' => '夏休みに友達と海に行きます。',
                'opsi_b_furigana' => 'なつやすみに ともだちと うみに いきます。',
                'opsi_b_romaji' => 'Natsuyasumi ni tomodachi to umi ni ikimasu.',
                'opsi_b_arti' => 'Saat liburan musim panas, saya pergi ke pantai bersama teman.',
                'opsi_c_kanji' => '彼は行きますピアノを弾きます。',
                'opsi_c_furigana' => ' かれは いきます ピアノを ひきます。',
                'opsi_c_romaji' => 'Kare wa ikimasu piano o hikimasu.',
                'opsi_c_arti' => 'Dia pergi main piano.',
                'opsi_d_kanji' => '行きます空が青いです。',
                'opsi_d_furigana' => 'いきます そらが あおいです。',
                'opsi_d_romaji' => ' Ikimasu sora ga aoi desu.',
                'opsi_d_arti' => 'Pergi langit itu biru. ',
                'jawaban_benar' => 'b',
            ],
            //end ikimasu

            //kimasu
 [
                'kosakata_id' => 'KOSA-008',
                'level' => 'intermediate',
                'soal_kanji' => ' 先生は何時に学校に____か？',
                'soal_furigana' => 'せんせいは なんじに がっこうに＿＿＿か?',
                'soal_romaji' => 'Sensei wa nanji ni gakkou ni ____ ka?',
                'soal_arti' => 'Guru ____ ke sekolah jam berapa?',
                'opsi_a_kanji' => '書きます',
                'opsi_a_furigana' => 'かきます',
                'opsi_a_romaji' => 'kakimasu',
                'opsi_a_arti' => 'menulis',
                'opsi_b_kanji' => '行きます',
                'opsi_b_furigana' => 'いきます',
                'opsi_b_romaji' => 'ikimasu',
                'opsi_b_arti' => 'pergi',
                'opsi_c_kanji' => '来ます',
                'opsi_c_furigana' => 'きます',
                'opsi_c_romaji' => 'kimasu',
                'opsi_c_arti' => 'datang',
                'opsi_d_kanji' => '飲みます',
                'opsi_d_furigana' => 'のみます',
                'opsi_d_romaji' => 'nomimasu',
                'opsi_d_arti' => ' minum',
                'jawaban_benar' => 'c',
            ],

             [
                'kosakata_id' => 'KOSA-008',
                'level' => 'advanced',
                'soal_kanji' => '',
                'soal_furigana' => '',
                'soal_romaji' => '',
                'soal_arti' => 'Pilih kalimat yang paling natural untuk penggunaan kosakata 来ます(きます)',
                'opsi_a_kanji' => '毎朝、友達が家に来ます。',
                'opsi_a_furigana' => 'まいあさ、ともだちが いえに きます。',
                'opsi_a_romaji' => ' Maiasa, tomodachi ga ie ni kimasu.',
                'opsi_a_arti' => 'Setiap pagi, teman datang ke rumah.',
                'opsi_b_kanji' => '来ます魚は泳ぎます。',
                'opsi_b_furigana' => 'きます さかなは およぎます。
。',
                'opsi_b_romaji' => 'Kimasu sakana wa oyogimasu.',
                'opsi_b_arti' => 'Datang ikan berenang. ',
                'opsi_c_kanji' => '彼は来ますご飯を食べます。',
                'opsi_c_furigana' => 'かれは きます ごはんを たべます。',
                'opsi_c_romaji' => 'Kare wa kimasu gohan o tabemasu.',
                'opsi_c_arti' => 'Dia datang makan nasi. ',
                'opsi_d_kanji' => '来ます空が青いです。',
                'opsi_d_furigana' => 'きます そらが あおいです。',
                'opsi_d_romaji' => 'Kimasu sora ga aoi desu.',
                'opsi_d_arti' => 'Datang langit itu biru.  ',
                'jawaban_benar' => 'a',
            ],

            //end kimasu

            //mimasu
   //kimasu
 [
                'kosakata_id' => 'KOSA-009',
                'level' => 'intermediate',
                'soal_kanji' => '新しい映画を____。',
                'soal_furigana' => 'あたらしい えいがを ____。',
                'soal_romaji' => ' Atarashii eiga o ____.',
                'soal_arti' => 'saya akan ____ film baru.',
                'opsi_a_kanji' => '書きます',
                'opsi_a_furigana' => 'かきます',
                'opsi_a_romaji' => 'kakimasu',
                'opsi_a_arti' => 'menulis',
                'opsi_b_kanji' => '泳ぎます',
                'opsi_b_furigana' => 'およぎます',
                'opsi_b_romaji' => 'oyogimasu',
                'opsi_b_arti' => 'berenang',
                'opsi_c_kanji' => '買います',
                'opsi_c_furigana' => 'かいます',
                'opsi_c_romaji' => 'kaimasu',
                'opsi_c_arti' => 'membeli',
                'opsi_d_kanji' => '見ます',
                'opsi_d_furigana' => 'みます',
                'opsi_d_romaji' => 'mimasu',
                'opsi_d_arti' => 'menonton',
                'jawaban_benar' => 'd',
            ],

               [
                'kosakata_id' => 'KOSA-009',
                'level' => 'advanced',
                'soal_kanji' => '',
                'soal_furigana' => '',
                'soal_romaji' => '',
                'soal_arti' => 'Pilih kalimat yang paling natural untuk penggunaan kosakata 見ます(みます)',
                'opsi_a_kanji' => '見ます空が青いです。',
                'opsi_a_furigana' => 'みます そらが あおいです。',
                'opsi_a_romaji' => 'Mimasu sora ga aoi desu.',
                'opsi_a_arti' => 'Melihat langit itu biru. ',
                'opsi_b_kanji' => '彼は見ますご飯を食べます。',
                'opsi_b_furigana' => 'かれは みます ごはんを たべます。',
                'opsi_b_romaji' => 'Kare wa mimasu gohan o tabemasu.',
                'opsi_b_arti' => 'Dia melihat makan nasi.  ',
                'opsi_c_kanji' => '毎晩新しいドラマを見ます。',
                'opsi_c_furigana' => 'まいばん あたらしい ドラマを みます。',
                'opsi_c_romaji' => 'Maiban atarashii dorama o mimasu.',
                'opsi_c_arti' => 'Saya menonton drama baru setiap malam.',
                'opsi_d_kanji' => '見ますコーヒーは熱いです。',
                'opsi_d_furigana' => 'みます コーヒーは あついです。',
                'opsi_d_romaji' => 'Mimasu koohii wa atsui desu.',
                'opsi_d_arti' => 'Melihat kopi itu panas. ',
                'jawaban_benar' => 'c',
            ],
            //end mimamsu

            //hon
             [
                'kosakata_id' => 'KOSA-010',
                'level' => 'intermediate',
                'soal_kanji' => '明日、新しい____を図書館に返します。',
                'soal_furigana' => 'あした、あたらしい ____ を としょかんに かえします。',
                'soal_romaji' => 'Ashita, atarashii ____ o toshokan ni kaeshimasu',
                'soal_arti' => 'Besok, saya akan mengembalikan ____ baru ke perpustakaan.',
                'opsi_a_kanji' => 'シャツ',
                'opsi_a_furigana' => 'シャツ',
                'opsi_a_romaji' => 'shatsu',
                'opsi_a_arti' => 'kemeja',
                'opsi_b_kanji' => '水',
                'opsi_b_furigana' => 'みず',
                'opsi_b_romaji' => 'mizu',
                'opsi_b_arti' => 'air',
                'opsi_c_kanji' => '本',
                'opsi_c_furigana' => 'ほん',
                'opsi_c_romaji' => 'hon',
                'opsi_c_arti' => 'buku',
                'opsi_d_kanji' => '机',
                'opsi_d_furigana' => 'つくえ',
                'opsi_d_romaji' => 'tsukue',
                'opsi_d_arti' => 'meja',
                'jawaban_benar' => 'c',
            ],
               [
                'kosakata_id' => 'KOSA-010',
                'level' => 'advanced',
                'soal_kanji' => '',
                'soal_furigana' => '',
                'soal_romaji' => '',
                'soal_arti' => 'Pilih kalimat yang paling natural untuk penggunaan kosakata 本(ほん)',
                'opsi_a_kanji' => '図書館で新しい本を読みます。',
                'opsi_a_furigana' => 'としょかんで あたらしい ほんを よみます。',
                'opsi_a_romaji' => 'Toshokan de atarashii hon o yomimasu.',
                'opsi_a_arti' => 'Saya membaca buku baru di perpustakaan. ',
                'opsi_b_kanji' => '本です空は青い。',
                'opsi_b_furigana' => 'ほんです そらは あおい。',
                'opsi_b_romaji' => 'Hon desu sora wa aoi.',
                'opsi_b_arti' => ' Buku itu langit biru.',
                'opsi_c_kanji' => '猫が本を走ります。',
                'opsi_c_furigana' => 'ねこが ほんを はしります。',
                'opsi_c_romaji' => 'Neko ga hon o hashirimasu.',
                'opsi_c_arti' => 'Kucing berlari buku. ',
                'opsi_d_kanji' => '本を車が飲みます。',
                'opsi_d_furigana' => 'ほんを くるまが のみます。',
                'opsi_d_romaji' => ' Hon o kuruma ga nomimasu.',
                'opsi_d_arti' => 'Mobil meminum buku. ',
                'jawaban_benar' => 'a',
            ],
            //end hon

        
          ];

        foreach ($soalkosakata as $soal) {
            DB::table('soal_kosakata')->insert([
                'kosakata_id' => $soal['kosakata_id'],
                'level' => $soal['level'],
                'soal_kanji' => $soal['soal_kanji'],
                'soal_furigana' => $soal['soal_furigana'],
                'soal_romaji' => $soal['soal_romaji'],
                'soal_arti' => $soal['soal_arti'],
                'opsi_a_kanji' => $soal['opsi_a_kanji'],
                'opsi_a_furigana' => $soal['opsi_a_furigana'],
                'opsi_a_romaji' => $soal['opsi_a_romaji'],
                'opsi_a_arti' => $soal['opsi_a_arti'],
                'opsi_b_kanji' => $soal['opsi_b_kanji'],
                'opsi_b_furigana' => $soal['opsi_b_furigana'],
                'opsi_b_romaji' => $soal['opsi_b_romaji'],
                'opsi_b_arti' => $soal['opsi_b_arti'],
                'opsi_c_kanji' => $soal['opsi_c_kanji'],
                'opsi_c_furigana' => $soal['opsi_c_furigana'],
                'opsi_c_romaji' => $soal['opsi_c_romaji'],
                'opsi_c_arti' => $soal['opsi_c_arti'],
                'opsi_d_kanji' => $soal['opsi_d_kanji'],
                'opsi_d_furigana' => $soal['opsi_d_furigana'],
                'opsi_d_romaji' => $soal['opsi_d_romaji'],
                'opsi_d_arti' => $soal['opsi_d_arti'],
                'jawaban_benar' => $soal['jawaban_benar'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
